### ISSUE TITLE
Behat parsing Test fails on MySQL

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-report_customsql#101]
MySQL 5.7
PHP 7.3
Moodle latest MOODLE_39_STABLE
executed with moodlehq/moodle-docker

Failed Behat test: Ad-hoc database queries report.View an Ad-hoc database query that returns data that confuses PHP CSV parsing
 ```
Error Details
And I view the "Test query" custom sql report: Moodle exception: Error when executing the query: Error reading from database (FUNCTION moodle.CHR does not exist SELECT CHR(92) AS Backslash, CHR(44) AS Comma LIMIT 0, 5001 [array ( )])More information about this error

Error when executing the query: Error reading from database (FUNCTION moodle.CHR does not exist
SELECT CHR(92) AS Backslash, CHR(44) AS Comma LIMIT 0, 5001
[array (
)])
More information about this error


    
×
    
Debug info: 
 
Error code: queryfailed
 (Exception)
```

I can see this was made to work here - https://github.com/moodleou/moodle-report_customsql/runs/3006877690
But it doesn't run that exact permutation and none are mysql

Haven't encountered it with an actual report though

**Comment by timhunt** [comment]
I'm sorry, but I don't care. This seems to be not entirely standardised, CHR works on MariaDB and Postgres, so I suggest you use one of those for your development (or patch your local copy of the pugin if you really need to run the tests with MySQL).

**Comment by timhunt** [comment]
My the way, if you can suggest a simple fix which works on all DBs, I would be happy to receive one.
