### ISSUE TITLE
Allow report results to be retrieved with a WS token vis /webservice/pluginfile.php

### ISSUE THREAD

**Issue by brendanheywood** [moodleou/moodle-report_customsql#105]
This replaces https://github.com/moodleou/moodle-report_customsql/issues/99

1) We will allow reports to be downloaded via /webservice/pluginfile.php endpoint given an existing WS token, eg:

/webservice/pluginfile.php/1/report_customsql/download/123?token=wstoken12345

2) The default dataformat will be used if none is provided. Optionally this can be set with a query param

/webservice/pluginfile.php/1/report_customsql/download/123?token=wstoken12345&dataformat=csv

2) This will download the latest copy of the report available if it a scheduled report, and fail if one doesn't exist
3) If it is an on demand report it will run it first
4) The url will not contain a timestamp and will not change
5) If the report has params placeholders they can optionally be provided as query params. If they are not provided the defaults are used

/webservice/pluginfile.php/1/report_customsql/download/123?token=wstoken12345&param1=foo&param2=bar

@abias I do not have permission to close #99 can you please do that.

**Comment by jwalits** [comment]
Hey @brendanheywood - would you be able to close this issue when you get a chance as the MR has already been merged in

Thanks
