### ISSUE TITLE
hyper links in reports return text

### ISSUE THREAD

**Issue by ecottis** [moodleou/moodle-report_customsql#119]
Hi 

For some reason reports do not convert url links from text the code is:

![image](https://user-images.githubusercontent.com/67025862/188253000-da75112f-06d8-42d1-80a3-08abdbf7375d.png)

This returns the following:
![image](https://user-images.githubusercontent.com/67025862/188252863-35eacd53-41d0-4598-8bf4-3a35df66367b.png)

I'm running on Moodle 4.0.3 and using the latest version of moodle-report_customsql

Any support or solution would be greatly appreciated

**Comment by timhunt** [comment]
Read the instructions on the form where you edit the query.

```sql
SELECT
    c.shortname,
    c.shortname AS Course_Name,
    CONCAT('%%WWWROOT/course/view.php%%Q%%id=', c.id) AS Course_Name_link_url,
    --- and so on
```
