### ISSUE TITLE
PHP 8.1 - strftime is deprecated

### ISSUE THREAD

**Issue by sharpchi** [moodleou/moodle-report_customsql#143]
There are a few lines where strftime is used, but got this exception in testing on PHP8.1

`Scheduled task failed: Ad-hoc database queries: run scheduled reports task (report_customsql\task\run_reports),Unknown error type: Function strftime() is deprecated in /var/www/html/report/customsql/locallib.php on line 611
Backtrace:
* line 611 of /report/customsql/locallib.php: call to behat_error_handler()
* line 64 of /report/customsql/classes/task/run_reports.php: call to report_customsql_delete_old_temp_files()
* line 263 of /lib/cronlib.php: call to report_customsql\task\run_reports->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 81 of /admin/cron.php: call to cron_run()`

The date() function should be a fairly simple replacement (with format adjustments).

**Comment by abias** [comment]
I think this issue was solved by https://github.com/moodleou/moodle-report_customsql/commit/a97a9e55196b95e2124444aff776c074cf6f95ef and could be closed.
