### ISSUE TITLE
Use branches instead of tags to denote moodle version compatibility

### ISSUE THREAD

**Issue by mark-webster-catalyst** [moodleou/moodle-report_customsql#146]
It's standard practice with moodle plugins to create branches of the format `MOODLE_XX_STABLE` for the minimum compatible version of the code. This makes updating to the latest compatible much easier as you can just pull the branch.

Would you be open to following this practice?

**Comment by timhunt** [comment]
That is one standard practice, used by some plugins.

The other standard practice is to have one version of the plugin code, which supports as many different Moodle versions as possible. That is the one I favour. (It is less work, and mostly I don't have time to maintain one branch per plugin, let alone multiple.)
