### ISSUE TITLE
Query does not return any result (with no error message) for large table 

### ISSUE THREAD

**Issue by djarran** [moodleou/moodle-report_customsql#157]
**Description:** Using this plugin to query the `book_chapters` table (~8gb in this instace, freakishly large) returns the following, no matter how simple the query:

![image](https://github.com/user-attachments/assets/d420e48a-6863-44ef-acf4-a7cafe2cea16)

While it is understandable given the size of the table, an error message would be good to display in cases like this

**Comment by timhunt** [comment]
I assume you have Moodle's Debugging set to 'Developer' level while invesitgating this.

With that, it means what it says: the query ran (with no errors) and returned no data.

This report uses exactly the same mechanism for accessing the database as the rest of Moodle does. So, if  Moodle can read this table, then so can this report.

I don't think there is a bug here, so closing this.
