### ISSUE TITLE
New collapsible list feature, fixes for PHP and Moodle errors and better support for multilingual sites

### ISSUE THREAD

**Issue by michael-milette** [moodleou/moodle-report_customsql#18]
Here is a summary of recent pull requests:

Fix #15 - When you have a lot of reports, the list can get pretty long. This adds a new Expand/Collapse link to the list of reports and enable users to just expand the section they are looking for. We have over 130 reports in this list on our own site.

Fix #16 - This addresses an issue that appears, with debugging set to developer mode, when you run a report for the first time because $report->lastrun was never previously set.

Fix #17 - Includes the following fixes:
* Moved $PAGE->set_url() and $PAGE->set_context() up so that they are always set - Avoids Moodle warnings in some situations.
* Report names are now processed through Moodle filters so that multilanguage tags will be processed on multilingual sites.
* Data content in reports is now processed through Moodle filter so that multilanguage tags will be processed on multilingual sites.

Let me know if you have any questions or concerns.

Best regards,

Michael Milette

**Comment by timhunt** [comment]
Discussions in the separate pull requests. Closing this.

**Comment by michael-milette** [comment]
Thanks Tim!
