### ISSUE TITLE
Moodle 2.7 not supported anymore?

### ISSUE THREAD

**Issue by eberhardt** [moodleou/moodle-report_customsql#22]
I'm wondering since 2.7 is still on LTS. So is it possible to create an extra branch for Moodle 2.7 users?

**Comment by timhunt** [comment]
Moodle 2.7 is not supported by the latest development version.

If you want a version compatible with Moodle 2.7, then you need to go back through history and find one (that is easy to see here https://moodle.org/plugins/pluginversions.php?plugin=report_customsql). If you want the latest features - well, sorry, but you can't have them with Moodle 2.7.

**Comment by eberhardt** [comment]
Ok, I did that in order to succeed with the update.
