### ISSUE TITLE
email report to non-moodle users?

### ISSUE THREAD

**Issue by frumbert** [moodleou/moodle-report_customsql#25]
We use this report to generate weekly reports but would like to send them directly to external bodies who aren't users in Moodle (and we don't want them to be). Is there a reason we can't just type in [for scheduled reports] one or more email addresses rather than having the specify a username of a moodle user?

**Comment by timhunt** [comment]
No real reason, I think, but emailing a real user is easier with the Moodle APIs. It's not that hard to create a user with auth type 'nologin' and the email address you want.
