### ISSUE TITLE
Component is not enabled

### ISSUE THREAD

**Issue by Arshad83** [moodleou/moodle-report_customsql#37]
I installed the plugin to  Ad-hoc database queries in Moodle 3.3 and gives error Component is not enabled (report_customsql). when I hit Run Now in Scheduled tasks.

**Comment by timhunt** [comment]
Did you install it completely? That is, after adding the new files to Moodle, did you go to Admin -> Notifications to let the install run? 

I just tested, and the plugin works fine here in Moodle 3.3.
