### ISSUE TITLE
Scheduled reports -> history

### ISSUE THREAD

**Issue by Kovinis** [moodleou/moodle-report_customsql#38]
Hi,
I have several scheduled reports. Everything is working fine, but one day I loogged to check the history of reports and it's gone. How is it possible?
Maybe job's deleted the history? Or when clearing cache report's history  was deleted?
![image](https://user-images.githubusercontent.com/17912549/50272235-c8cf7280-043f-11e9-9707-e5bb648b2d60.png)

**Comment by timhunt** [comment]
The report history is stored in moodledata, in a folder called admin_report_customsql. There is no code to clean that up. The only way it could happen would be if someone with direct access to the server deleted it.

**Comment by Kovinis** [comment]
> The report history is stored in moodledata, in a folder called admin_report_customsql. There is no code to clean that up. The only way it could happen would be if someone with direct access to the server deleted it.
Thank You. But why in Moodle Interface the report history is not showing?

**Comment by timhunt** [comment]
Did you check on the server? Is that folder still there?

**Comment by Kovinis** [comment]
Yap, everything is in a place.
