### ISSUE TITLE
Consider using site calendar start of week configuration

### ISSUE THREAD

**Issue by paulholden** [moodleou/moodle-report_customsql#44]
Moodle [contains configuration](https://docs.moodle.org/36/en/Calendar_settings#Start_of_week) for setting the day to be used for start of the week.

Rather than hardcoding Saturday as the start of the week, would it be worth observing existing site configuration?

**Comment by timhunt** [comment]
This is worth considering, but I am afraid that it is not as simple as that.

It seems that on the OU servers, core Moodle first day of week is set to Sunday, but we want our weekly reports to be run on a Saturday. I have asked my colleagues if we want to change any of that.

It might be good to stop hard-coding this, however. Perhaps one option would be to make a new admin setting for report_customsql 'Day to run weekly reports'. And, that could include an option -1 => "Use Start of week from the Calendar settings (Monday)" which could even be the default.

By the way, I like the unit tests you wrote in this patch.

**Comment by paulholden** [comment]
Hi @timhunt, thanks for the feedback. I guess our use cases are slightly different; we have Monday set as the start of the week, so weekly reports would run from Monday 00:00 to Sunday 23:59

If you were running your reports on the Saturday wouldn't you be doing the same thing? i.e. previous Sunday 00:00 to current Saturday 23:59? I may have misinterpreted what the report plugin uses this value for.

**Comment by timhunt** [comment]
No. For us, Moodle config calendar_startwday is 0 == Sunday, but REPORT_CUSTOMSQL_START_OF_WEEK is 6 == Satruday. This may not make sense, but it is what we have got, and we don't want to change the behaviour of all our reports, so I can't merge your patch.

(I like the unit test changes, by the way.)

So, if you want to get this in, please can you do a version which adds a new admin setting for the custom SQL report. That could have choices: -1 => Use default (_Show value in brackets_), 0 => Sunday, ... 6 => Saturday.

Thanks.

**Comment by paulholden** [comment]
> So, if you want to get this in, please can you do a version which adds a new admin setting for the custom SQL report. That could have choices: -1 => Use default (_Show value in brackets_), 0 => Sunday, ... 6 => Saturday.

Hi Tim, I've implemented this as described (see new pull request https://github.com/moodleou/moodle-report_customsql/pull/65) - default value uses the site calendar start of week, or a specific day can be selected if required
