### ISSUE TITLE
URL within results not working for particular query

### ISSUE THREAD

**Issue by davidpesce** [moodleou/moodle-report_customsql#54]
Related to issue #34 

I've inherited a Moodle site with an existing report that worked prior to this commit: https://github.com/moodleou/moodle-report_customsql/commit/7c36255009fcbebf464cee90e16e2e0d79b4275b

I agree whole-heartedly with the commit and think the solution is excellent. Unfortunately, I'm not able to get the query to display as URLs. I'm including a simplified/sanitized version of what I'm looking to do (below). 

The goal of this is to display links taht an admin can click to execute a series of tasks via Moodle web services.

```
SELECT student,
  CASE WHEN links.type = 'suspend' THEN 'site' ELSE shortname END AS course,
  links.type AS action,
'Execute Action' as execute,
  CASE WHEN links.type = 'unenrol' THEN ugly.unenrol
    WHEN links.type = 'unassign_role' THEN ugly.unassign_role
	WHEN links.type = 'suspend' THEN ugly.suspend END
 AS execute_link_url

FROM(
	SELECT student, shortname,

	CONCAT(
	'%%WWWROOT%%/webservice/rest/server.php%%Q%%moodlewsrestformat=json&wstoken=',
	token.data,
	'&wsfunction=enrol_manual_enrol_users&enrolments[0][roleid]=5&enrolments[0][userid]=',
	active.userid,
	'&enrolments[0][courseid]=',
	active.courseid,
	'&enrolments[0][suspend]=1&enrolments[0][timeend]=',
	UNIX_TIMESTAMP()
	) AS unenrol,


	CONCAT(
	'%%WWWROOT%%/webservice/rest/server.php%%Q%%moodlewsrestformat=json&wstoken=',
	token.data,
	'&wsfunction=core_role_unassign_roles&unassignments[0][roleid]=5&unassignments[0][userid]=',
	active.userid,
	'&unassignments[0][contextlevel]=course&unassignments[0][instanceid]=',
	active.courseid
	) AS unassign_role,

	CONCAT(
	'%%WWWROOT%%/webservice/rest/server.php%%Q%%moodlewsrestformat=json&wstoken=',
	token.data,
	'&wsfunction=core_user_update_users&users[0][suspended]=1&users[0][id]=',
	active.userid,
	'&users[0][customfields][0][type]=Status&users[0][customfields][0][value]=',
	statuses.status,
        '&users[0][customfields][1][type]=Returned&users[0][customfields][1][value]=1'
	) AS suspend

	FROM
	(SELECT CONCAT(u.firstname,' ',u.lastname) AS student, ue.userid, e.courseid, c.shortname
	FROM {user} u
	  JOIN {user_enrolments} ue ON ue.userid = u.id
		JOIN {enrol} e ON ue.enrolid = e.id
		  JOIN {course} c ON e.courseid = c.id
			JOIN {course_categories} cc ON c.category = cc.id
	WHERE u.id = :userid
	  AND cc.path LIKE '/42/43%' ) AS active
	JOIN (
	    SELECT 'token' AS data
	) AS token
	JOIN (
	    SELECT 'Suspended' AS status
	    UNION SELECT 'Withdraw' AS status
	    UNION SELECT 'Cancel' AS status
	    UNION SELECT 'Administrative Cancel' AS status
	    UNION SELECT 'LoA' AS status
	) AS statuses ON statuses.status = :status
) AS ugly
JOIN (
  SELECT 'unenrol' AS type
  UNION SELECT 'unassign_role'
  UNION SELECT 'suspend'
) AS links
GROUP BY student, course, action
ORDER BY action DESC
```

**Comment by timhunt** [comment]
Well, the query is written in a fairly funny way. It would be easier to work with if there weren't so many differnet layers of nested queries.

However, it looks right. You have one column **execute** containing some suitable text ('Execute Action') and a second column **execute_link_url**. If you run the query directly on the database, what does it return? Seeing the first few rows of that might help debug the problem.

Ah! I think I found it. There is a group by clause. You might need to change taht to match the SELECT. Perhpas that needs to be

GROUP BY student, course, action, execute, execute_link_url

That is a bit of a guess.

**Comment by timhunt** [comment]
If that does not work, make a copy of the query, and try simplifying it as much as possible while still showing the bug. Trying to find a minimal example might help detect whether there is a bug in the code (and it would then be clearer what the bug is) or a problem in the query.

**Comment by davidpesce** [comment]
Thanks for the suggestion! Unfortunately, it didn't work. I'll make a duplicate of the report and do as you suggested. Stay tuned!

**Comment by timhunt** [comment]
Any update on this?

**Comment by timhunt** [comment]
Closing. If there is still an problem, please create a new issue. This is currently working for me.
