### ISSUE TITLE
Reusable parameters?

### ISSUE THREAD

**Issue by frumbert** [moodleou/moodle-report_customsql#58]
When executing a scheduled report, you can re-use the %%STARTTIME%% and %%ENDTIME%% parameters, which is great. Can this plugin support reusable parameters for on-demand reports too?

```sql
SELECT
   u.firstname GivenName,
   u.lastname Surname,
   u.email Email,
   u.username UserID,
   s.fullname Course,
   CASE
      WHEN
         c.`timeenrolled` > 0 
         THEN
         from_unixtime(c.`timeenrolled`, '%D %M %Y %h:%i:%s') 
         ELSE
         'Never' 
      END
      Started, 
   CASE
      WHEN
         c.`timecompleted` > 0 
         THEN
         from_unixtime(c.`timecompleted`, '%D %M %Y %h:%i:%s') 
         ELSE
         'Never' 
      END
      Completed 
   FROM
   {user} u 
      LEFT OUTER JOIN
         {course_completions} c 
            ON u.id = c.`userid` 
         INNER JOIN
         {course} s 
            ON (c.`course` = s.`id` and c.id in (select id from {course_completions} where
timecompleted between %%STARTTIME%% and %%ENDTIME%% or timeenrolled between %%STARTTIME%% and %%ENDTIME%%))
   WHERE
      u.auth = 'manual'
```
e.g. I'd like to reuse the start and end date selector:

```sql
timecompleted between :date_started and :date_completed or timeenrolled between :date_started and :date_completed))
```

**Comment by timhunt** [comment]
I think that the way to handle your case is with a subquery, to get the values you want to use mulitple times into columns. E.g.

SELECT *
FROM course_completions
JOIN (SELECT :date_started AS starttime, :date_started AS endtime) dates ON 1 = 1
WHERE timecompleted between dates.starttime and dates.endtime
OR timeenrolled between dates.starttime and dates.endtime

**Comment by frumbert** [comment]
Hmm, yes that's a clever way of thinking of it - cheers

**Comment by timhunt** [comment]
So, can we close this one?
