### ISSUE TITLE
No longer receiving email notifications for daily reports

### ISSUE THREAD

**Issue by rayhinton** [moodleou/moodle-report_customsql#60]
Hi Tim and OU team,

Been using this plugin for years and have gotten a lot of use out of it! I recently upgraded to Version build number 3.6 for Moodle 3.3+ (2018112200) yesterday, and I think something changed that is causing us to not receive email notifications about daily reports. For full disclosure, we upgraded from Moodle 3.5 to Moodle 3.6.5+ (Build: 20190718) at the same time, so I am wondering if my issue is related to potential differences in the way Messaging works.

**Expected behavior:** I expect that my query, which has been running daily and sending email notifications with the same settings for at least a couple years, would continue to send daily email notifications.

**Changes:** 
* upgraded from Moodle 3.5 (3.5.5 I think) to Moodle 3.6.5+ (Build: 20190718), and 
* latest version of customsql plugin available on moodle.org [Version build number 3.6 for Moodle 3.3+ (2018112200)](https://moodle.org/plugins/pluginversion.php?id=18326)
* did not change any customsql plugin settings

**Observed behavior:**
* no longer receiving the same daily email notifications
* making a new test query, and then running the scheduled task manually via CLI, produced this output with exception message

```
$ sudo /usr/bin/php schedule_task.php --execute='\report_customsql\task\run_reports'
Execute scheduled task: Ad-hoc database queries: run scheduled reports task (report_customsql\task\run_reports)
... Looking for old temp CSV files to delete.
... Running report daily in the past
!!! Exception - Argument 1 passed to message_send() must be an instance of core\message\message, instance of stdClass given, called in [dirroot]/report/customsql/locallib.php on line 714 !!!
```

I was also looking at the commit history on GitHub, and noticed there was a commit dcfc300 from April or May that mentioned the Messaging API, and indeed, it also changed the $eventdata initialization to a different class (`$eventdata = new \core\message\message();`).

Should the latest version that is published on moodle.org work, or does it need to have that later commit applied? Let me know if I can help clarify or provide any other information.

**Comment by paulholden** [comment]
@rayhinton - this is the same as was reported in https://github.com/moodleou/moodle-report_customsql/issues/42 and fixed in the commit you've linked to (you should upgrade 🙂)

**Comment by rayhinton** [comment]
Indeed @paulholden , we just upgraded yesterday, and I got the usual daily email this morning! I will close this now.
