### ISSUE TITLE
Return users who are configured to receive emailed reports in privacy provider

### ISSUE THREAD

**Issue by paulholden** [moodleou/moodle-report_customsql#67]
Currently their username may be stored in a reports configuration as to who it should be emailed to - this may be considered as 'data stored about a user'?

May need to take into account https://github.com/moodleou/moodle-report_customsql/issues/66 if that is worked on

**Comment by timhunt** [comment]
Technically, yes we should. Thank you for noticing this omission.

However, such users are almost certainly staff of your institution, and so have probably agreed to have work-related data stored about them. Therefore fixing this is lower priority. Still, pull requests welcome.

**Comment by timhunt** [comment]
The fix for this has been pushed.
