### ISSUE TITLE
Change character delimiter in CSV file

### ISSUE THREAD

**Issue by tifabapar** [moodleou/moodle-report_customsql#68]
When a CSV file of a query is downloaded it comes with the char "," as a delimiter of the columns.
Brazilian CSV uses the ";" char as the delimiter.
Moodle have its own library for writing CSV files and it allow the choice of the separator.
Many countries have different separator, it's necessary to include the option to choose the character delimiter or to use Moodle's CSV library.
Moodle forum: https://moodle.org/mod/forum/discuss.php?d=392545

**Comment by timhunt** [comment]
Latest version will allow export in a range off ormats using Moodle's data export library, so hopefully this will be fixed.
