### ISSUE TITLE
FR: Allow more fine grained control over who can access which query

### ISSUE THREAD

**Issue by danowar2k** [moodleou/moodle-report_customsql#70]
Ours is a site with 50000+ users.

The current methods to authorize access to all queries are a few capabilities which a user can or cannot have in a context.

With regards to privacy it would be really useful if you could implement a fine grained control over who can access which query. For example, there are some queries we would provide that should only be accessible to users A and B while another query should only be accessible to users B and C.

Every query would have 0..* users which can access it.
A user would only see the queries s/he has access to.

**Comment by timhunt** [comment]
For that sort of fine-grained control, perhaps you would be better with the 'configurable reports' block: https://moodle.org/plugins/block_configurable_reports

**Comment by danowar2k** [comment]
Okay, I'll close this then.
