### ISSUE TITLE
SQL cannot contain a literal ? inside strings

### ISSUE THREAD

**Issue by brendanheywood** [moodleou/moodle-report_customsql#74]
I'm pretty sure this is a core bug, but there is a workaround

Something like this should work, and produce a url you can click on:

```
SELECT id
FROM {course}
concat('https://moodle.com/course/view.php?id=', id)
```

This feels like a regression, I thought I used to do this all the time but it no longer works, and git says its always been like this:

Error when executing the query: ERROR: Incorrect number of query parameters. Expected 1, got 0.

Core code:
https://github.com/moodle/moodle/blob/master/lib/dml/moodle_database.php#L901

I worked around this in another plugin by parsing the sql and replacing all inline strings containing a ? with a param:

https://github.com/catalyst/moodle-local_datacleaner/commit/47e506438068635eb51baf1853c272cb3fb86621

**Comment by timhunt** [comment]
It has always been like this. And, you need to read the text on the page where you edit the query.

There are various tokens you can use, and for precisely this reason there are tokens %%C%% for colon and %%Q%% for questionmark.

And, yes, it is a core thing. This is not the most transparent work-around, but it is easy to understand, so I am not inclined to change it.

**Comment by brendanheywood** [comment]
Ah! thanks
