### ISSUE TITLE
Download these results as .CSV results in Unknown download file error 

### ISSUE THREAD

**Issue by jpbennett** [moodleou/moodle-report_customsql#76]
I have recently installed and started to use the Ad-hoc database queries plugin.  Today I ran the report "Cohorts by user"; it returned 653 rows.  However, when I then opted to download the results as a .CSV file I encountered a Unknown download file error.

I have tried to find details about this issue and how best to resolve it without success.  Please help.

**Comment by timhunt** [comment]
Discussing this in the plugins DB, so closing this.

**Comment by jpbennett** [comment]
Hi Tim,
Reopening this issue as you requested on the Ad-hoc database queries plugin page comments:

We have been working to debug the issue on our moodle site, during which we have observed the following:
* The timestamp is being turned into a filename in a function called report_customsql_temp_cvs_name in locallib.php, which is called from both the view.php and download.php files.
* view.php is the report view, where you have the option to download the various types of reports.
* download.php is the PHP script that is supposed to return the file or display the error message.

The timestamp is the exact same when the function is called from view.php and download.php, but the filename that is created based on the timestamp is 5 hours different in the view.php instance than the download.php instance, even though it is the same function.

We suspect the download function fails because of the difference in the timestamp.

Any ideas? Your feedback is most welcome.

Thank you!

Paul
