### ISSUE TITLE
Download these results as .CSV results in Unknown download file error

### ISSUE THREAD

**Issue by jpbennett** [moodleou/moodle-report_customsql#78]
Hi Tim,

Re-submitting issue first reported in https://github.com/moodleou/moodle-report_customsql/issues/76#issue-692162201 as you requested in the Ad-hoc database queries plugin page comments.

We have been working to debug the issue on our moodle site, during which we have observed the following:

The timestamp is being turned into a filename in a function called report_customsql_temp_cvs_name in locallib.php, which is called from both the view.php and download.php files.
view.php is the report view, where you have the option to download the various types of reports.
download.php is the PHP script that is supposed to return the file or display the error message.
The timestamp is the exact same when the function is called from view.php and download.php, but the filename that is created based on the timestamp is 5 hours different in the view.php instance than the download.php instance, even though it is the same function.

We suspect the download function fails because of the difference in the timestamp.

Any ideas? Your feedback is most welcome.

Thank you!

Paul

**Comment by timhunt** [comment]
Yes, the failure will be due to the different time-stamps.

The bug will be that some time-stamps are being generated with UTC, and others with server local time, and it needs to be made consistent.

**Comment by jpbennett** [comment]
Hi Tim,

More info for you from our further attempts to trace the cause of this timezone discrepancy:

We found the ultimate issue: Logstore xAPI.  This plugin is autoloading a file that sets the timezone to 'Europe/London'.  It is NOT EVEN ENABLED in the our Moodle site, as shown in the screenshot below from Site administration > Plugins > Logging > Manage log stores, but because of the way that Moodle builds the admin menu, the plugin's settings are getting loaded automatically.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/19594528/94007105-ea753080-fd6e-11ea-958f-2f4c04e2446f.png)

**Comment by timhunt** [comment]
Thanks for reporting back.

Does that mean that this is a bug in Logstore xAPI, and there is no issue with this plugin?

**Comment by jpbennett** [comment]
Unsure. I am going to uninstall the xAPI plugin and see if this remedies the situation.

**Comment by jpbennett** [comment]
Success. It appears that the Logstore xAPI is the cause of the timezone conflict that interferes with the ability of the Ad-hoc database queries plugin to download report output as .CSV.  Hopefully the owners of the Logstore xAPI plugin can fix that problem.

**Comment by jpbennett** [comment]
Thank you for your assistance and patience while working with us to resolve this issue.

**Comment by timhunt** [comment]
Thanks for reporting back. Closing this now.
