### ISSUE TITLE
Download fails with debug enabled in Moodle 3.9

### ISSUE THREAD

**Issue by golenkovm** [moodleou/moodle-report_customsql#81]
Hi team,

We've found an issue with download. When debugging is enabled `download.php` calls `download_as_dataformat()` which is deprecated as part of MDL-68500 in 3.9 and then fails on https://github.com/moodle/moodle/blob/ff2b655928da2a0deeddc5b6a9ecf95981482b33/lib/classes/dataformat.php#L68 as buffer holds debugging message.

![image](https://user-images.githubusercontent.com/22066290/99743912-c9d91500-2b2a-11eb-92d1-df472f69d8f2.png)

**Comment by golenkovm** [comment]
We can simply replace `download_as_dataformat` by `\core\dataformat::download_data`, but this will make master branch incompatible with Moodle 3.8 and older. As the plugin repo doesn't have branches for stables, maybe it's better to check the version and then call `download_as_dataformat` or `\core\dataformat::download_data` depending on the version check result.

**Comment by timhunt** [comment]
We have a fix for this internally at the OU. We just have not had time to push it publicly yet (not helped by https://github.com/moodlehq/moodle-plugin-ci/issues/47). We should update the repo here soon.

**Comment by timhunt** [comment]
I am just in the process of pushing the fix for this. Sorry it took so long.
