### ISSUE TITLE
Emailto can be broken by default values

### ISSUE THREAD

**Issue by Peterburnett** [moodleou/moodle-report_customsql#89]
When creating a new scheduled report, the page will load fine, however saving this report with no recipients for email, then editing the report will end up with an extra empty value being loaded into the HTML in the set_data function of the edit_form.

![image](https://user-images.githubusercontent.com/21162968/120946054-853b6100-c77e-11eb-8ce9-a6cad97aa174.png)

If you then add a recipient to the report, and save it, the implode function will save an empty string as the first element, which will then break when attempting to send the emails via cron, as it will try and convert the empty element to a userid then user, which causes a DB exception.

![image](https://user-images.githubusercontent.com/21162968/120946164-e9f6bb80-c77e-11eb-8524-783f36407f94.png)

**Comment by timhunt** [comment]
We've already fixed this locally, just not had time to push our fix to github. Sorry.

**Comment by Peterburnett** [comment]
Hi @timhunt 
Are you able to push this patch up soon? I am hoping not to have to fork the plugin to work around this issue.
Thanks in advance!
