### ISSUE TITLE
Allow sql to include the same named param multiple times

### ISSUE THREAD

**Issue by brendanheywood** [moodleou/moodle-report_customsql#96]
There are all sorts of reasons why you want a singe filter eg :courseid but reuse that param in multiple places in the sql

**Comment by timhunt** [comment]
That is a Moodle core issue. We just directly use the Moodle database library.

There are tricky to achieve this. The example you give is easy. Include {course} in the list of tables joined, and have WHERE c.id = :courseid. Then you can use c.id everywhere.

So, I think it is feasible to do this.

**Comment by brendanheywood** [comment]
thanks @timhunt - are you aware of any trackers where this was attempted to be fixed in core? Or discussion around why it wasn't?

**Comment by timhunt** [comment]
I think becuase 'That's how DBs work natively'. Person most likely to recall is Eloy, but you could as in Moodle Dev Chat.
