### ISSUE TITLE
If a report requires params, you cannot link from view to the edit page

### ISSUE THREAD

**Issue by brendanheywood** [moodleou/moodle-report_customsql#97]
Ie visit view.php and you see the form to enter the params, but there is no way from this page to get to the edit page. It should have the same footer as a normal report page which has no params

**Comment by timhunt** [comment]
Patches welcome.

**Comment by timhunt** [comment]
Re that last issue. Did you set it to be a scheduled report?

**Comment by timhunt** [comment]
Anyway, this was a good idea, so I have implemented it locally:

![image](https://user-images.githubusercontent.com/138653/132877940-b0d98f3e-03aa-4ea9-ba8a-c41dc7e268dc.png)

Will get pushed publically sometime after we have finished testing.

**Comment by brendanheywood** [comment]
So I hadn't touched this since I tried last time, I just tried again:

1) uninstall plugin
2) reinstall latest main branch
3) upgrade with default admin settings
4) Create a new report, the only fields I fill in are a 'Query name' of 'test' and the sql with 

```
select id,firstname
from {user}
```
then save and same weird result: "This query has not yet been run."

The file names of the sql which is written is not the same file name it is trying to read it from a few dozen lines later. After some debugging discovered than the timezone is changing mid script:

![image](https://user-images.githubusercontent.com/187449/132938656-4f1ca244-698a-46e1-a560-8d7cfc4f20b9.png)

And it gets changed back to Australia time when calling format_string

```
echo $OUTPUT->heading(format_string($report->displayname));
```

The weird thing is it shouldn't ever be london time. Debugging earlier the timezone is getting messed up into london time when calling admin_externalpage_setup.

Following that rabbit hole it looks like its somewhere in admin_get_root(). I'll come back to this later, but it looks like its probably a core bug as I'm running on the latest master core branch, or maybe some other plugin is doing weird stuff.

**Comment by timhunt** [comment]
Good detective work. No idea why it is doing that. Of course, we are in London time here, which might be why we don't see this.

**Comment by brendanheywood** [comment]
Nailed it! Its another plugin messing it up:

https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/utils/create_timestamp.php#L20

Logged it:

https://github.com/xAPI-vle/moodle-logstore_xapi/issues/802

**Comment by timhunt** [comment]
Fix for this (original issue, not the side-track) being pushed. Closing this.
